### ISSUE TITLE
Existentials in struct fields

### ISSUE THREAD

**Issue by ranjitjhala** [liquid-rust/flux#156]
The code below fails

```rust
pub struct Bob {
    #[flux::field(RVec<i32>{n:n>0})]
    elems: RVec<i32>,
}
```

fails with 

```
  |
9 |     #[flux::field(RVec<i32>{n:n>0})]
  |                             ^ expected 0 arguments, found 1
```

Is this a bug? Or is there some reason we can't have existentials in struct fields?

**Comment by nilehmann** [comment]
Did some digging and the problem seems to be that we are reaching this point https://github.com/liquid-rust/flux/blob/main/flux-desugar/src/desugar.rs#L524 with an empty `AdtSorts`. Function signatures are desugared latter in the pipeline which explains why the existential is working for functions but not structs, but I still don't understand why we don't have `AdtSorts` filled by the time we desugar structs.
