### ISSUE TITLE
`flux::assume` is wrong

### ISSUE THREAD

**Issue by cole-k** [liquid-rust/flux#220]
Right now if we annotate a function with `#[flux::assume]`, it shouldn't check the inner body. However, it currently does. The known workaround is to annotate the function with `#[flux::sig]`.

This appears to be a regression.

**Comment by nilehmann** [comment]
I reimplemented the previous behavior here https://github.com/liquid-rust/flux/pull/222, but I'm keeping this open because now I'm unsure about what the correct behavior for `flux::assume` should be. 

`flux::assume` is doing two things.

1. Completely ignoring the code of the function
1. Assuming the function has the annotated type

I think liquid haskell has two different attributes to control this `ignore` and `assume`, but I can't think of any scenario in which you would want an `assume` without an `ignore`. Perhaps a better name for the attribute is `trusted` as in prusti.

**Comment by cole-k** [comment]
Why not have three annotations:

1. `flux::trusted` is sugar for `flux::ignore` + `flux::assume`
2. `flux::ignore` does what LH's `ignore` does
3. `flux::assume` does what LH's `assume` does

We would expect the latter two to be used infrequently. I could imagine there is some benefit to being able to completely ignore part of the code, no?

**Comment by nilehmann** [comment]
Maybe we can have just two `flux::trusted` and `flux::assume`. I'm thinking the word _trusted_ can both imply "I'm trusting this code so I'm not checking it" and "I'm trusting this signature so I won't check it". Then you have

```rust
// we don't check the function and use the default signature
#[flux::trusted]
fn ipa(x: i32) -> i32 {
    ...
}

// we don't check the function and use `fn(i32) -> i32{v: v > 0}` as its type
#[flux::trusted]
#[flux::sig(fn(i32) -> i32{v: v > 0})]
fn ris(x: i32) -> i32{
   ...
}
```

Then `flux::assume` would be used as
```rust
// assume the function has type `fn(i32) -> i32{v: v >0}` but also check its body
// against the default rust signature in hope that could catch some errors
#[flux::assume]
#[flux::sig(fn(i32) -> i32{v: v > 0)]
fn hipa(x: i32) -> i32 {
   ...
}

// this doesn't make sense, we should report an error or a warning
#[flux::assume]
fn ira(x: i32) -> i32 {
   ...
}
```

Finally, `flux::trusted` implies `flux::assume` so there's no ambiguity if they are used together, but we should probably show at least a  warning if they are.

The implementation in https://github.com/liquid-rust/flux/pull/222 gives `flux::assume` the meaning I'm giving to `flux::trusted` here, so we could go ahead and change the name. I believe the meaning I'm giving to `flux::assume` here is weird in practice so I wouldn't implement it until we have a specific need for it.
