### ISSUE TITLE
Allow `@`-binders in outputs

### ISSUE THREAD

**Issue by ranjitjhala** [liquid-rust/flux#239]
We often want to allow `@n`-binders in outputs (i.e. write signatures like 

  `(…) -> exists n. T`

for example a signature like

```rust
  fn () -> (i32[@n], Vec<i32{v: 0 <= v && v < n}>)
```

that says the function produces a pair of some integer and a bunch of numbers in `0..n`. 

Here, the function itself *internally* determines what the `n` is so we 

* Can not use a `forall`-input that is *resolved* at the “caller” but
* Must use a `exists`-output that is *generated* at the call site (and of course *resolved* at the return site of the function body if we are checking it…)

**Comment by nilehmann** [comment]
@ranjitjhala do you have a specific example in mind that requires this? 

While the semantics of existentials in return position is clear to me, I'm a bit hesitant about whether we should abuse the `@n`  syntax. Maybe this is an advance enough (uncommon) use case to require an explicit `exists` for clarity over conciseness. 

Additionally, the particular example you posted could also be expressed with a "dependent pair". Strictly speaking, I think we only need existentials in position `(...) -> exists n. ...` if `n` is going to be mentioned both in the return type and `ensures` clauses.

**Comment by ranjitjhala** [comment]
The "use-case" I have in mind was motivated by the kani/firecracker post

https://github.com/model-checking/kani/blob/main/tests/cargo-kani/firecracker-block-example/src/main.rs

but also the pattern in the motivating example for the "implicit refinement types" paper.

in essence, you have an api call that does some internal computation and returns: 
* some value V and 
* some other associated value that "depends on" V.

So you want to give the output type the signature something like:

```rust
foo (p: &strg Thing) -> exists N. i32{v: ... depends on N ... } ensures p: Thing[@N]
```

or the other way around the `i32[@N]` and the `p: Thing[... depends on N...]`
 

V, ... stuffyou have to _also_ that that

**Comment by nilehmann** [comment]
Not exactly the same thing, but I believe we should be able to support a general type `exists n. T` for any type `T`, provided that `n` appears in a [proper position](https://arxiv.org/pdf/2209.13000v1.pdf). I believe this could be used to desugars various syntaxes, e.g., dependent pairs as in the example in the original post. If the binder can be mentioned both in the return type and the ensures clauses, then the problem is different because we cannot simply desugar it as a type, but it is a related problem.

In anticipation, I already started some related work here https://github.com/liquid-rust/flux/tree/evars. It refactors the way we infer parameters at function calls. So, instead of inferring  parameters first and then checking subtyping, we first generate fresh evars and then unify them during subtyping. I believe this will be useful to support existentials in more positions.

**Comment by ranjitjhala** [comment]
Another use-case that shows up in `wave` (AFAICT) -- you have a method that takes in two `&mut RVec` of **equal size** and then pushes stuff into both (or pops from both) -- so simpler version is:

```rust 
fn foo(x: &mut i32, y: &mut i32, b: bool) {
  if b {
     *x += 1;
     *y += 1;
  }
}  
```

So you'd want a signature like:

```rust
fn (x: &strg i32[@n], y: &strg i32[n]) ensures x: i32[#m], y: i32[m]
``` 

(using `#m` to denote the "output" or "existential" instead of the input `@n`)

**Comment by nilehmann** [comment]
If we decide on the surface syntax this should be easy to implement after https://github.com/liquid-rust/flux/pull/281

**Comment by ranjitjhala** [comment]
Some choices (am not particularly wedded to anything)

```rust
// Use explicit exists
fn (x: &strg i32[@n], y: &strg i32[n]) ensures exists m. x: i32[m], y: i32[m]

// Use `@` in the output
fn (x: &strg i32[@n], y: &strg i32[n]) ensures x: i32[@m], y: i32[m]

// Use some other symbol in the output eg
fn (x: &strg i32[@n], y: &strg i32[n]) ensures x: i32[#m], y: i32[m]
```

My suggestion would be to start with "explicit exists" and then if it gets too tedious/important enough, it will probably be easy to modify `desugar` to support
either of the other options?

**Comment by nilehmann** [comment]
The problem with exists is that I don't really know where to put it to make clear what's the scope. Ideally, it should range over the ensures clauses and the return type, but it is weird when combined with `requires`

```rust
fn() -> exists x. R
requires p
ensures q
```

I want the `exists` to be over the return type `R` and the ensure predicate `q`.

**Comment by ranjitjhala** [comment]
Do we _really_ need a `requires` anymore?

**Comment by ranjitjhala** [comment]
Or maybe then we should use the `#` to distinguish output binders (which WF will check cannot appear in the requires...)

**Comment by ranjitjhala** [comment]
The `#` would also address the odd _asymmetry_ of using `exists` (when we don't use a `forall`)...

**Comment by nilehmann** [comment]
There's one neat use of requires that you can't do with constrained types,  you can define `unreachable` as:

```rust
fn unreachable()
requires false
```
instead of
```rust
fn unreachable(_: {() : false})
```
which makes it more comfortable to use.

Other than that it's not strictly necessary, but I do find it sometimes clearer to specify the relationships between inputs in a requires clause. 

I don't hate nor love `#`. In the interest of experimenting with the feature, I would go for it since it seems to have a clearer meaning.

**Comment by ranjitjhala** [comment]
agree on all points!
