### ISSUE TITLE
Add support for rust Array length `Const`

### ISSUE THREAD

**Issue by ranjitjhala** [liquid-rust/flux#254]
My initial reaction was that indexing arrays by the length would cause inconsistencies as you could write an array where the indexed length is different than the const length

```rust
#[flux::sig(fn([i32; _][2]))]
fn myarr(a: [i32; 1]) {
    a[1]
}
```
But if array literal are the only way to construct arrays then I think this should be ok and it just declaring an inhabited type. However, not connecting both lengths makes code cumbersome. For example, it makes it impossible to use the result of a function like https://doc.rust-lang.org/std/primitive.u32.html#method.to_be_bytes without explicitly checking the length, even though you already know the length is 4. Ideally, arrays shouldn’t be indexed but rather we the const length should be automatically _reflected_ into the logic when needed, i.e., the typing rule for `Len` should be something like

```
|- a: [T; n]         reflect(n) = a
———————————————————————————--———-——-
          |- Len(a): usize[a]
```
I’m ok with leaving the implementation like this for now as doing this reflection requires further design.

_Originally posted by @nilehmann in https://github.com/liquid-rust/flux/pull/252#pullrequestreview-1221901911_

**Comment by ranjitjhala** [comment]
It seems to me that we should be able to support this by:

1. Preserve the `Const` in the `ty::TyKind::Array` (ie. https://doc.rust-lang.org/beta/nightly-rustc/rustc_middle/ty/enum.TyKind.html)

2. Remove the indexing (pull out of `BaseTy`)

3. Instead use [`try_eval_usize`](https://doc.rust-lang.org/beta/nightly-rustc/rustc_middle/ty/struct.Const.html#method.try_eval_usize) to get index?

[Maybe we could just store the `usize` in our representation i.e. change our

```rust
pub struct Const;
``` 

to `pub struct Const(usize);` ?

**Comment by nilehmann** [comment]
That should get us far but it's actually a bit more complicated. There are also some technical details.

1. An array length is not always something that can be evaluated to an int, in particular, it can be a generic const, e.g.,
```rust
fn first<const n: usize>(arr: [i32; n]) {
    arr[0]
}
```
We should also handle generic consts (*). Further, the length could in theory be an arbitrary const expression, so I'm not sure exactly in which cases `try_eval_usize` fails. In practice, const generics are very restricted so it may be the case that an array length is always something that can be evaluated to an int or a generic const.

2. I don't know how to explain this very well, but if you go and try to implement this you'll hit a wall, because there's no place in the pipeline where we can easily call `try_eval_usize`.

1 we can leave for future work, but for 2 we need some redesign.

(*) The interaction between const code and refinements still eludes me, but there's probably something principled we should be able to do. For example, in the same way, we currently support global const (e.g., `const x: i32 = 0`) inside refinements, we should be able to support generic consts inside refinements 
```rust
#[flux::sig(fn(arr: [i32; n], i: usize{i > n}) -> i32)]
fn<const n: usize>get(arr: [i32; n], i: usize) -> i32 {
    arr[i]
}
```

**Comment by ranjitjhala** [comment]
Hmm I managed to get a bunch of stuff working (including the eval stuff) I
am almost done but am pulling Array out of BaseTy so we don’t have
“useless” indices - let me push and you can take a look?

**Comment by ranjitjhala** [comment]
Perhaps the ParamEnv hack works for the simple cases only?
