### ISSUE TITLE
Unexpected panic in subtyping...

### ISSUE THREAD

**Issue by ranjitjhala** [liquid-rust/flux#268]
Triggered by the code below ... 

```rust
#![feature(register_tool)]
#![register_tool(flux)]

#[path = "../lib/rvec.rs"]
mod rvec;
use rvec::RVec;

#[flux::refined_by(reserve_len: int, counter: int)]
pub struct FdMap {
    #[flux::field(RVec<usize>[@reserve_len])]
    pub reserve: RVec<usize>,
}

#[flux::sig(fn (&mut FdMap[@dummy], k: usize) )]
pub fn delete(fdmap: &mut FdMap, k: usize) {
    fdmap.reserve.push(k); // triggers a crash at flux-typeck/src/constraint_gen.rs:360:18
}
```

which produces this

```
thread 'rustc' panicked at 'internal error: entered unreachable code: `&mut RVec<usize{}>[a0]` <: `ptr(mut, ?e0#0)` at Some(flux-tests/tests/todo/FdMap.rs:16:5: 16:26 (#0))', flux-typeck/src/constraint_gen.rs:360:18
```

**Comment by nilehmann** [comment]
The reason is that the function expects a strong reference but you only have a mutable one. This (again) can be solved by implementing opening of mutable references (seeing a mutable reference as strong during the duration of the lifetime). Maybe I should add implementing this to my new year's resolutions.

Note that the signature `fn(&mut FdMap[@dummy], k: usize)` is wrong because the function doesn't preserve the size of the vector, thus you could avoid the `panic` by taking a strong reference and _exposing_ the updated length in the ensures clause. Then, whether to take strong vs mutable references (provided that we implement opening of mutable references) is a matter of encapsulation, you either expose the length or not.

**Comment by ranjitjhala** [comment]
Hmm interesting - at any rate it seems this should be user facing error not
a panic?

**Comment by nilehmann** [comment]
Yes, I always wanted to implement it so I never bother making it a user facing error.

**Comment by ranjitjhala** [comment]
Ah, ok sounds good let me close. The thing that motivated this issue works, but the original problem still remains, namely:

```rust
ctx.fdmap.delete(...)
```

causes a 

``` 
panicked at 'expected type at Some(src/wrappers.rs:98:5: 98:27 (#0))', flux-typeck/src/type_env/paths_tree.rs:568:23
```

which requires me to do make the `delete` a method of `ctx` and do `ctx.fdmap_delete`...
