### ISSUE TITLE
Allow matching on references

### ISSUE THREAD

**Issue by ranjitjhala** [liquid-rust/flux#294]
The following code

```rust
#![feature(register_tool)]
#![register_tool(flux)]

pub fn foo(z: &mut Option<i32>) -> i32 {
    match z {
        Some(n) => 1,
        None => 0,
    }
}
```

currently fails with at 

```
panicked at 'expected adt at flux-tests/tests/todo/match-mut-ref.rs:5:11: 5:13 (#0)'
```

(I added a span on a local branch...)

Any clues on how to proceed here @nilehmann ? (I thought `*z` might work but it doesn't ... )

**Comment by nilehmann** [comment]
I think this is a regression introduced in https://github.com/liquid-rust/flux/pull/272/files#diff-af38b7fa008d5c45cf415587ca0baeaa01eb4d955cdb1f9493e69bea58a25675, but more generally is another instance of "we are not opening mutable references" (see https://github.com/liquid-rust/flux/issues/158#issuecomment-1272290926). In this case, because the `Option<i32>` doesn't have any indices we can work around it unpacking inside the `&mut`, but if we had opening of mutable references then we wouldn't have to make this distinction.

**Comment by ranjitjhala** [comment]
Thanks!!!
